eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

#gelen tum isteklerde jwt dogrulamas覺 yap覺ls覺n
#jwt'nin issuer'i keycloak
#bff'ten gelen jwt burada dogrulan覺r
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8585/realms/smartorder-bff-dev