spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: order-service-route
              uri: lb://order-service
              predicates:
                - Path=/api/v1/orders/**
            - id: product-service-route
              uri: lb://product-service
              predicates:
                - Path=/api/v1/product/**

server:
  port: 8888

eureka:
  register-with-eureka: true
  fetch-registry: true