eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#oauth2 client -> kullan覺c覺 ad覺na 'keycloak kullanarak' token al覺r.
spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8585/realms/smartorder-bff-dev    #oidc discovery (.well-known/openid-configuration)
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: bff-web
            client-secret: elGMuGWwXZybKGGrCp3ECKPHr4usmVsU
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope:
              - openid
              - profile
              - email