eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8585/realms/smartorder-bff
            user-name-attribute: preferred-username
        registration:
          keycloak:
            client-id: bff-web
            client-secret: PjBXL5URha1gL97vsYZrBWbMhMOKFOVy
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope:
              - openid
              - profile
              - email