eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka

spring:
  security:     #bff-service'i keycloak'a tanitiyoruz
    oauth2:
      client:
        provider:  #keycloak bir provider (auth providerı)
          keycloak:
            issuer-uri: http://keycloak:8585/realms/turkcell-p1-docker #keycloak'ın çalıştığı adres
            user-name-attribute: preferred-username
        registration:
          keycloak:
            client-id: bff-service    #keycloak'ta olusturdugumuz client'in id'si.     (confidential-client)
            client-secret: 7HsdDmDiHtZkpOr87cmZI6YGWlWD5b40  #client'e atanmıs secret
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"   #baseUrl:http://localhost:8989, registrationId:keycloak
            authorization-grant-type: authorization_code
            scope:          #giriş yapmıs kullanıcıdan hangi bilgileri alalım
              - openid      #jwt bilgileri icin gerekli
              - profile
              - email