eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8585/realms/turkcell-p1-dev

  #db config (postgresql)
  datasource:
    url: jdbc:postgresql://localhost:5434/customer_service_db
    username: postgres
    password: customerservice_db_password
  #hibernate & orm
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    format-sql: true