eureka:
  client:
    service-url:
      defaultZone : http://discovery-server:8761/eureka

spring:
  datasource:
    url: jdbc:postgresql://ordersv_db:5432/order_service_db
    username: postgres
    password: orderservice_db_password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    format-sql: true

  kafka:
    bootstrap-servers: kafka:9092
  cloud:
    stream:
      kafka:
        binders:
          brokers: kafka:9092
      bindings:
        orderCreated-out-0:
          destination: order-topic
          contentType: application/json