eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka

spring:
  kafka:
    bootstrap-servers: localhost:9092
  cloud:
    stream:
      kafka:
        binders:
          brokers: localhost:9092
      bindings:
        orderCreated-out-0:
          destination: order-topic
          contentType: application/json