eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka

spring:
  kafka:
    bootstrap-servers: host.docker.internal:9094
  cloud:
    stream:
      kafka:
        binders:
          brokers: host.docker.internal:9094
      bindings:
        orderCreated-out-0:
          destination: order-topic
          contentType: application/json