eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka

spring:
  datasource:
    url: jdbc:postgresql://productsv_db:5432/product_service
    username: postgres
    password: productservice_db_password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true
    format-sql: true