#bu link development'a özel.
eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product_service_db
    username: postgres
    password: productservice_db_password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    format-sql: true
